### ISSUE TITLE
Trying to adapt this.

### ISSUE THREAD

**Issue by steeljardas** [EOSArgentina/ueosio#4]
I'm trying to adapt this to use the purchasesale contract from atomicmarket but I'm not being successful.

```
tx2 = {"actions":[{
    	"account":"atomicmarket",
    	"name":"purchasesale",
	        "data":{
	        "buyer": "steelhardgod", 
	        "sale_id":"18776635", 
	        "intended_delphi_median":"0", 
	        "taker_marketplace": "''"
	        },"authorization":[{
			"actor":"steelhardgod",
	        "permission":"owner"
	        }]}]}


info = requests.get('https://wax.greymass.com/v1/chain/get_info').json()
ref_block_num, ref_block_prefix = get_tapos_info(info['last_irreversible_block_id'])
chain_id = info['chain_id']


data2 = tx2['actions'][0]['data']
ds2 = DataStream()
ds2.pack_name(data2['buyer'])
ds2.pack_string(data2['sale_id'])
ds2.pack_string(data2['intended_delphi_median'])
ds2.pack_string(data2['taker_marketplace'])


tx2['actions'][0]['data'] = binascii.hexlify(ds2.getvalue()).decode('utf-8')


tx2.update({
    "expiration": get_expiration(datetime.utcnow(), timedelta(minutes=15).total_seconds()),
    "ref_block_num": ref_block_num,
    "ref_block_prefix": ref_block_prefix,
    "max_net_usage_words": 0,
    "max_cpu_usage_ms": 0,
    "delay_sec": 0,
    "context_free_actions": [],
    "transaction_extensions": [],
    "context_free_data": []
})


auth2 = tx2['actions'][0]['authorization'][0]
private_key = "5Kxxxxxxxxxxxxxxxxxxxxxxxx"

tx_id, tx2 = sign_tx(
   chain_id,
   tx2,
   private_key,
)
ds2 = DataStream()
ds2.pack_transaction(tx2)
packed_trx = binascii.hexlify(ds2.getvalue()).decode('utf-8')


tx2 = build_push_transaction_body(tx2['signatures'][0], packed_trx)

# Push transaction
res = requests.post('https://wax.greymass.com/v1/chain/push_transaction', json=tx2).json()
```

I get the error

`{'code': 500, 'message': 'Internal Service Error', 'error': {'code': 3050003, 'name': 'eosio_assert_message_exception', 'what': 'eosio_assert_message assertion failure', 'details': [{'message': 'assertion failure with message: read', 'file': 'wasm_interface.cpp', 'line_number': 1131, 'method': 'eosio_assert'}, {'message': 'pending console output: ', 'file': 'apply_context.cpp', 'line_number': 113, 'method': 'exec_one'}]}}`

I tried removing the datastreams because I don't understand how they worked but when I did I just kept getting the error "This sale_id doesn't exist" even though it 100% existed and wasn't bought yet.

**Comment by steeljardas** [comment]
Managed to fix, it was due to the DataStream types, however, is there a way to push multiple actions in python in a single transaction??

**Comment by elmato** [comment]
> Managed to fix, it was due to the DataStream types, however, is there a way to push multiple actions in python in a single transaction??

Yes, you can add any number of actions to the "actions" transaction field

**Comment by steeljardas** [comment]
> > Managed to fix, it was due to the DataStream types, however, is there a way to push multiple actions in python in a single transaction??
> 
> Yes, you can add any number of actions to the "actions" transaction field

Do you have any examples of how it works? because I'm not too sure how I'd setup the DataStream if there are multiple Data

**Comment by steeljardas** [comment]
Also do you maybe have discord or telegram so I can DM you if you don't mind?

**Comment by elmato** [comment]
https://t.me/EOSarg
